quarkus:
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://
    username: 
    password: 

  grpc:
    clients:
      usuario:
        port: 7002
        host: 
        
      financieros:
        port: 7001
        host: 

  http:
    port: 8083
